# Generated by Django 4.0.4 on 2022-06-05 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=uuid.UUID('403af951-3cb8-4776-8953-566c3b64ac1b'), max_length=100, primary_key=True, serialize=False)),
                ('c_title', models.CharField(max_length=50)),
                ('c_lenght', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.CharField(default=uuid.UUID('fc7f788c-d0a5-4201-b76b-9f81b4d59c42'), max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preentregaApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id', models.CharField(default=uuid.UUID('4b6b24e5-ffb8-4d67-a83d-184e56ff2de1'), max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preentregaApp.course')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preentregaApp.professor')),
            ],
        ),
    ]
